version: "3.2"

volumes:
  esdata:
    driver: local

services:

  redis:
    image: redis:3.2-alpine
    volumes:
      -  ./data/redis:/data
    ports:
      - "6380:6379"
    networks:
      - owl-local-dev

  mysql:
    image: mysql:5.6
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=owl
      - MYSQL_DATABASE=owl
      - MYSQL_USER=owl
      - MYSQL_PASSWORD=owl
    ports:
      - "8082:3306"
    networks:
      - owl-local-dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - owl-local-dev

networks:
  owl-local-dev:
