version: "3.2"

services:
  api:
    container_name: 'owl_api'
    build: ./application/api
    restart: 'on-failure'
    ports:
      - '8080:8080'ls
    networks:
      - owl-local-dev
      
  redis:
    image: redis:3.2-alpine
    volumes:
      -  ./data/redis:/data
    ports:
      - "6380:6379"
    networks:
      - owl-local-dev

  mysql:
    image: mysql:5.6
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=owl
      - MYSQL_DATABASE=owl
      - MYSQL_USER=owl
      - MYSQL_PASSWORD=owl
    ports:
      - "8082:3306"
    networks:
      - owl-local-dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    restart: always
    container_name: notification_elasticsearch
    environment:
      - node.name=notification
      - cluster.name=notification-cluster
      - http.port=9200
      - transport.tcp.port=9300
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - http.cors.enabled=true
      - node.data=true
      - node.master=true
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - owl-local-dev

networks:
  owl-local-dev:
