version: "3.2"

services:

  redis:
    image: redis:3.2-alpine
    volumes:
      -  ./data/redis:/data
    ports:
      - "6380:6379"
    networks:
      - owl-local-dev

  mysql:
    image: mysql:5.6
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=owl
      - MYSQL_DATABASE=owl
      - MYSQL_USER=owl
      - MYSQL_PASSWORD=owl
    ports:
      - "8082:3306"
    networks:
      - owl-local-dev

networks:
  owl-local-dev:
